"""Add subscription dates to Bakery

Revision ID: 8e9fdbc476ab
Revises: b5e93b5600b8
Create Date: 2026-08-15 17:23:14.570749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e9fdbc476ab'
down_revision: Union[str, Sequence[str], None] = 'b5e93b5600b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bakeries', sa.Column('subscription_start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bakeries', sa.Column('subscription_end_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bakeries', 'subscription_end_date')
    op.drop_column('bakeries', 'subscription_start_date')
    # ### end Alembic commands ###
