"""Add ERP features

Revision ID: b0ff51f424aa
Revises: f923b7158a1f
Create Date: 2026-08-14 16:38:57.900961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0ff51f424aa'
down_revision: Union[str, Sequence[str], None] = 'f923b7158a1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_batches_id'), 'inventory_batches', ['id'], unique=False)
    op.alter_column('bakeries', 'razorpay_key_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('bakeries', 'razorpay_key_secret',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('inventory_items', sa.Column('barcode', sa.String(), nullable=True))
    op.add_column('inventory_items', sa.Column('low_stock_threshold', sa.Float(), nullable=True))
    op.create_index(op.f('ix_inventory_items_barcode'), 'inventory_items', ['barcode'], unique=False)
    op.add_column('invoices', sa.Column('cgst_amount', sa.Float(), nullable=False))
    op.add_column('invoices', sa.Column('sgst_amount', sa.Float(), nullable=False))
    op.add_column('invoices', sa.Column('igst_amount', sa.Float(), nullable=False))
    op.alter_column('invoices', 'payment_link_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('invoices', 'bakery_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'invoices', 'bakeries', ['bakery_id'], ['id'])
    op.drop_index(op.f('ix_customers_bakery_id'), table_name='parties')
    op.drop_index(op.f('ix_customers_id'), table_name='parties')
    op.drop_index(op.f('ix_customers_name'), table_name='parties')
    op.create_index(op.f('ix_parties_bakery_id'), 'parties', ['bakery_id'], unique=False)
    op.create_index(op.f('ix_parties_id'), 'parties', ['id'], unique=False)
    op.create_index(op.f('ix_parties_name'), 'parties', ['name'], unique=False)
    op.add_column('purchases', sa.Column('cgst_amount', sa.Float(), nullable=False))
    op.add_column('purchases', sa.Column('sgst_amount', sa.Float(), nullable=False))
    op.add_column('purchases', sa.Column('igst_amount', sa.Float(), nullable=False))
    op.alter_column('recipes', 'image_data',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.alter_column('recipes', 'image_data',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('purchases', 'igst_amount')
    op.drop_column('purchases', 'sgst_amount')
    op.drop_column('purchases', 'cgst_amount')
    op.drop_index(op.f('ix_parties_name'), table_name='parties')
    op.drop_index(op.f('ix_parties_id'), table_name='parties')
    op.drop_index(op.f('ix_parties_bakery_id'), table_name='parties')
    op.create_index(op.f('ix_customers_name'), 'parties', ['name'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'parties', ['id'], unique=False)
    op.create_index(op.f('ix_customers_bakery_id'), 'parties', ['bakery_id'], unique=False)
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.alter_column('invoices', 'bakery_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('invoices', 'payment_link_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('invoices', 'igst_amount')
    op.drop_column('invoices', 'sgst_amount')
    op.drop_column('invoices', 'cgst_amount')
    op.drop_index(op.f('ix_inventory_items_barcode'), table_name='inventory_items')
    op.drop_column('inventory_items', 'low_stock_threshold')
    op.drop_column('inventory_items', 'barcode')
    op.alter_column('bakeries', 'razorpay_key_secret',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('bakeries', 'razorpay_key_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_inventory_batches_id'), table_name='inventory_batches')
    op.drop_table('inventory_batches')
    # ### end Alembic commands ###
