"""Add selling_price to Recipe

Revision ID: b5e93b5600b8
Revises: c9f83cbbbced
Create Date: 2026-08-15 15:19:45.519384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5e93b5600b8'
down_revision: Union[str, Sequence[str], None] = 'c9f83cbbbced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('selling_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'selling_price')
    # ### end Alembic commands ###
