"""Add recipe and bakery overhead columns

Revision ID: c9f83cbbbced
Revises: b0ff51f424aa
Create Date: 2026-08-15 14:20:38.794507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9f83cbbbced'
down_revision: Union[str, Sequence[str], None] = 'b0ff51f424aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bakeries', sa.Column('base_hourly_labor_rate', sa.Float(), nullable=True))
    op.add_column('bakeries', sa.Column('energy_cost_per_hour', sa.Float(), nullable=True))
    op.add_column('bakeries', sa.Column('misc_overhead_percentage', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('delivery_date', sa.DateTime(), nullable=True))
    op.add_column('recipes', sa.Column('prep_time_minutes', sa.Float(), nullable=True))
    op.add_column('recipes', sa.Column('bake_time_minutes', sa.Float(), nullable=True))
    op.add_column('recipes', sa.Column('use_custom_overheads', sa.Boolean(), nullable=True))
    op.add_column('recipes', sa.Column('custom_labor_cost', sa.Float(), nullable=True))
    op.add_column('recipes', sa.Column('custom_overhead_cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'custom_overhead_cost')
    op.drop_column('recipes', 'custom_labor_cost')
    op.drop_column('recipes', 'use_custom_overheads')
    op.drop_column('recipes', 'bake_time_minutes')
    op.drop_column('recipes', 'prep_time_minutes')
    op.drop_column('orders', 'delivery_date')
    op.drop_column('bakeries', 'misc_overhead_percentage')
    op.drop_column('bakeries', 'energy_cost_per_hour')
    op.drop_column('bakeries', 'base_hourly_labor_rate')
    # ### end Alembic commands ###
